#!/usr/bin/env perl                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                
use strict;                                                                                                                                                                                                                                     
use warnings;                                                                                                                                                                                                                                   
use feature 'say';                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                
use Data::Dumper;                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                
{                                                                                                                                                                                                                                               
  package Vic::Trie;                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                
  use warnings;                                                                                                                                                                                                                                 
  use strict;                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                
  sub new {                                                                                                                                                                                                                                     
    my ($class, $options) = @_;                                                                                                                                                                                                                 
    my $self->{head} = {};                                                                                                                                                                                                                      
    bless $self, $class;                                                                                                                                                                                                                        
    return $self;                                                                                                                                                                                                                               
  }                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                
  sub add {                                                                                                                                                                                                                                     
    my ($self, $word) = @_;                                                                                                                                                                                                                     
    my $curr = $self->{head};                                                                                                                                                                                                                   
    foreach my $c (split //, $word) {                                                                                                                                                                                                           
      if (not exists $curr->{$c}) {                                                                                                                                                                                                             
        $curr->{$c} = {};                                                                                                                                                                                                                       
      }                                                                                                                                                                                                                                         
      $curr = $curr->{$c};                                                                                                                                                                                                                      
    }                                                                                                                                                                                                                                           
    $curr-> {'*'} = 1;                                                                                                                                                                                                                          
  }                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                
  sub search {                                                                                                                                                                                                                                  
    my ($self, $word) = @_;                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                
    my $curr = $self->{head};                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                
    foreach my $c (split //, $word) {                                                                                                                                                                                                           
      return 0 unless exists $curr->{$c};                                                                                                                                                                                                       
      $curr = $curr->{$c};                                                                                                                                                                                                                      
    }                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                
    if (exists $curr->{'*'}) {                                                                                                                                                                                                                  
      return 1;                                                                                                                                                                                                                                 
    }                                                                                                                                                                                                                                           
    else {                                                                                                                                                                                                                                      
      return 0;                                                                                                                                                                                                                                 
    }                                                                                                                                                                                                                                           
  }                                                                                                                                                                                                                                             
}                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                
my $vic = Vic::Trie->new;                                                                                                                                                                                                                       
$vic->add('123');                                                                                                                                                                                                                               
$vic->add('123456');                                                                                                                                                                                                                            
$vic->add('123456789');   
                                                                                                                                                                                                                                                
($vic->search('123')) ? say "Yup" : say "Nope";                                                                                                                                                                                                 
($vic->search('1234')) ? say "Yup" : say "Nope";                                                                                                                                                                                                
($vic->search('123456')) ? say "Yup" : say "Nope";                                                                                                                                                                                              
($vic->search('123456789')) ? say "Yup" : say "Nope";                                                                                                                                                                                           
($vic->search('1234567890')) ? say "Yup" : say "Nope";                                                                                                                                                                                          
                                                                                                                                                                                                                                                
say Dumper $vic;                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                
                           
